# Generated by Django 5.1.4 on 2025-02-16 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
